# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.cache/wt [current_project]
set_property parent.project_path C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/SignZeroExtend.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/Selector5.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/Selector32.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/RegisterFile.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/PC.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/InstructionMemory.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/DataMemory.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/head.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/ControlUnit.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/ALU.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/CLOCK.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/SingleCycleCPU.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/PressKey.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/display.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/DispData.v
  C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/sources_1/new/BasysSingleCycleCPU.v
}
read_xdc C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/constrs_1/new/singlecyclecpu.xdc
set_property used_in_implementation false [get_files C:/Users/43787/Desktop/Vivado/SingleCycleCPU-Basys3/SingleCycleCPU.srcs/constrs_1/new/singlecyclecpu.xdc]

synth_design -top BasysSingleCycleCPU -part xc7a35tcpg236-1
write_checkpoint -noxdef BasysSingleCycleCPU.dcp
catch { report_utilization -file BasysSingleCycleCPU_utilization_synth.rpt -pb BasysSingleCycleCPU_utilization_synth.pb }
