# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.cache/wt [current_project]
set_property parent.project_path C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/SignZeroExtend.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/selector_3to1.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/selector_2to1.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/RegisterFile.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/PC.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/IR.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/InstructionMemory.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/DBDR.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/DataMemory.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/BDR.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/ALUOutDR.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/ALU.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/ADR.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/head.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/ControlUnit.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/PressKey.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/display.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/DispData.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/CLOCK.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/MultipleCycleCPU.v
  C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/sources_1/new/MultipleCPUBasys.v
}
read_xdc C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/constrs_1/new/MultipleCycleCPUBasys.xdc
set_property used_in_implementation false [get_files C:/Users/43787/Desktop/Vivado/MultipleCPU-Basys3/Multiple-CPU/Multiple-CPU.srcs/constrs_1/new/MultipleCycleCPUBasys.xdc]

synth_design -top MultipleCPUBasys -part xc7a35tcpg236-1
write_checkpoint -noxdef MultipleCPUBasys.dcp
catch { report_utilization -file MultipleCPUBasys_utilization_synth.rpt -pb MultipleCPUBasys_utilization_synth.pb }
